 // {
 //    courseName: "Course 1",
 //    country: "UK",
 //    university: "Placeholder University",
 //    campus: "Main Campus",
 //    level: "Bachelor's",
 //    scholarship: "Up to 50%",
 //    tuitionFees: "10,000",
 //  },

const courses = [
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Upto 10000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Construction Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },

  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "MSc in IT for Business Data Analytics",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc in Strategic Marketing",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc in Strategic Finance",
    country: "Hungary",
    university: "International Business School",
    campus: "International Business School",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc in Strategic",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc in Strategic Human Resource Management",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc in International Management",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseName: "MSc Physics",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseName: "MSc Molecular Biology",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseName: "MSc ​Hydrobiology - Water Quality Management",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },

  {
    courseName: "MSc Geoinformatic",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseName: "Course 2",
    country: "BD",
    university: "Example BD University",
    campus: "Main Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
];

export { courses };
