// {
//     courseName: "Course 1",
//     country: "UK",
//     university: "Placeholder University",
//     campus: "Main Campus",
//     level: "Bachelor's",
//     scholarship: "Up to 50%",
//     tuitionFees: "10,000",
// },

const courses = [
  {
    courseName: "Course 1",
    country: "UK",
    university: "Placeholder University",
    campus: "Main Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "UK",
    university: "Placeholder University",
    campus: "Main Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Placeholder University",
    campus: "Second Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Placeholder University",
    campus: "Second Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Placeholder University",
    campus: "Third Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Placeholder University",
    campus: "Third Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },

  {
    courseName: "Course 1",
    country: "UK",
    university: "Example University",
    campus: "Main Example Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "UK",
    university: "Example University",
    campus: "Main Example Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Second Example Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Second Example Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Third Example Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Third Example Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 1",
    country: "BD",
    university: "BD University",
    campus: "Main BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "BD",
    university: "BD University",
    campus: "Main BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Second BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Second BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Third BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Third BD Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },

  {
    courseName: "Course 1",
    country: "BD",
    university: "Example BD University",
    campus: "Main Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "BD",
    university: "Example BD University",
    campus: "Main Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
];

export { courses };
