 // {
 //    courseName: "Course 1",
 //    country: "UK",
 //    university: "Placeholder University",
 //    campus: "Main Campus",
 //    level: "Bachelor's",
 //    scholarship: "Up to 50%",
 //    tuitionFees: "10,000",
 //  },

const courses = [
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centres",
    level: "Undergraduate",
    scholarship: "Upto 10000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Construction Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },

  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Second Example Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Third Example Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "UK",
    university: "Example University",
    campus: "Third Example Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 1",
    country: "BD",
    university: "BD University",
    campus: "Main BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "BD",
    university: "BD University",
    campus: "Main BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Second BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Second BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Third BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "BD University",
    campus: "Third BD Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },

  {
    courseName: "Course 1",
    country: "BD",
    university: "Example BD University",
    campus: "Main Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 2",
    country: "BD",
    university: "Example BD University",
    campus: "Main Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Master's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Second Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "Bachelor's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
  {
    courseName: "Course 3",
    country: "BD",
    university: "Example BD University",
    campus: "Third Example BD Campus",
    level: "High School's",
    scholarship: "Up to 50%",
    tuitionFees: "10,000",
  },
];

export { courses };
