// {
//      courseId: 1,
//     courseName: "Course 1",
//     country: "UK",
//     university: "Placeholder University",
//     campus: "Main Campus",
//     level: "Bachelor's",
//     scholarship: "Up to 50%",
//     tuitionFees: "10,000",
// },

const courses = [
  {
    courseId: 1,
    courseName:
      "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseId: 2,
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Upto 10000",
    tuitionFees: "$15931",
  },
  {
    courseId: 3,
    courseName:
      "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Skilled Trades Regional Training Centre",
    level: "Undergraduate",
    scholarship: "Up to $1000",
    tuitionFees: "$15931",
  },
  {
    courseId: 4,
    courseName: "Strategic Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 5,
    courseName: "Construction Project Management",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 6,
    courseName:
      "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 7,
    courseName:
      "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 8,
    courseName:
      "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 9,
    courseName:
      "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "CANADA",
    university: "St. Clair College",
    campus: "Main Windsor Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },
  {
    courseId: 10,
    courseName: "MSc in IT for Business Data Analytics",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 11,
    courseName: "MSc in Strategic Marketing",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 12,
    courseName: "MSc in Strategic Finance",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 13,
    courseName: "MSc in Strategic",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 14,
    courseName: "MSc in Strategic Human Resource Management",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 15,
    courseName: "MSc in International Management",
    country: "Hungary",
    university: "International Business School",
    campus: "Budapest",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€12800",
  },
  {
    courseId: 16,
    courseName: "MSc Physics",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseId: 17,
    courseName: "MSc Molecular Biology",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseId: 18,
    courseName: "MSc ​Hydrobiology - Water Quality Management",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseId: 19,
    courseName: "MSc Geoinformatic",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Postgraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€7500",
  },
  {
    courseId: 20,
    courseName: "BSc ​Physics",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },
  {
    courseId: 21,
    courseName: "BSc Mathematics",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },
  {
    courseId: 22,
    courseName: "BSc ​Geography",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },
  {
    courseId: 23,
    courseName: "BSc Earth Sciences",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },
  {
    courseId: 24,
    courseName: "BSc Chemistry",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },

  {
    courseId: 25,
    courseName: "Foundation Program Business",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Foundation",
    scholarship: "TBA",
    tuitionFees: "€8000",
  },

  {
    courseId: 26,
    courseName: "BSc Applied Data Science",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€8000",
  },

  {
    courseId: 27,
    courseName: "BSc International Management",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€8000",
  },

  {
    courseId: 28,
    courseName: "BBA Tourism and Hospitality Management",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€8000",
  },

  {
    courseId: 29,
    courseName: "BSc International Management with Professional Experience",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€7700",
  },

  {
    courseId: 30,
    courseName: "BBA Tourism, Hotel Management & Operations",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€8000",
  },

  {
    courseId: 31,
    courseName: "MSc in Management",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€6000",
  },

  {
    courseId: 32,
    courseName: "Master of Business Administration (MBA)",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€10500",
  },

  {
    courseId: 33,
    courseName: "MSc in International Tourism Management",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€6000",
  },

  {
    courseId: 34,
    courseName: "MSc in Sustainable Development, Management and Policy",
    country: "Austria",
    university: "Modul University",
    campus: "Vienna",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€6000",
  },

  {
    courseId: 35,
    courseName: "BSc Chemistry",
    country: "Hungary",
    university: "University of Debrecen",
    campus: "Hungary",
    level: "Undergraduate",
    scholarship: "30% of annual fees",
    tuitionFees: "€6500",
  },

  {
    courseId: 36,
    courseName:
      "Honours Bachelor of Business Administration (Information Communication Technology)",
    country: "Canada",
    university: "St. Clair College",
    campus: "Chatham Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },

  {
    courseId: 37,
    courseName:
      "Honours Bachelor of Applied Arts in Social Justice & Legal Studies",
    country: "Canada",
    university: "St. Clair College",
    campus: "Chatham Campus",
    level: "Undergraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },

  {
    courseId: 38,
    courseName: "Master of Computer Science",
    country: "Canada",
    university: "Algoma University",
    campus: "Brampton",
    level: "Postgraduate",
    scholarship: "Upto 10000 CAD",
    tuitionFees: "$15931",
  },

  {
    courseId: 39,
    courseName: "Justice",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 40,
    courseName: "Computer Engineering",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 41,
    courseName: "Law",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 42,
    courseName: "Logistics",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 43,
    courseName: "Guidance and Psychological Counselling",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 44,
    courseName: "Business Administration",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 45,
    courseName: "Information System Engineering",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Undergraduate",
    scholarship: "TBA",
    tuitionFees: "€5500",
  },

  {
    courseId: 46,
    courseName: "Masters of Business Administration (MBA)",
    country: "Cyprus",
    university: "Cyprus West University",
    campus: "North Cyprus",
    level: "Postgraduate",
    scholarship: "TBA",
    tuitionFees: "€6000",
  },

  {
    courseId: 47,
    courseName: "Ms International Marketing",
    country: "Malta",
    university: "College de Paris",
    campus: "Malta",
    level: "Postgraduate",
    scholarship: "Not Available right now",
    tuitionFees: "€6500",
  },

  {
    courseId: 48,
    courseName: "Bachelor in Business Administration",
    country: "Malta",
    university: "College de Paris",
    campus: "Malta",
    level: "Undergraduate",
    scholarship: "Not Available right now",
    tuitionFees: "€11000",
  },

  {
    courseId: 49,
    courseName: "Bachelor in Interior Design",
    country: "Malta",
    university: "College de Paris",
    campus: "Malta",
    level: "Undergraduate",
    scholarship: "Not Available right now",
    tuitionFees: "€11000",
  },

  {
    courseId: 50,
    courseName: "Bachelor in Interior Design",
    country: "Malta",
    university: "College de Paris",
    campus: "Malta",
    level: "Undergraduate",
    scholarship: "Not Available right now",
    tuitionFees: "€11000",
  },
];

export default courses;
